chore: sync with keeweb/keeweb

diff --git a/.github/workflows/deploy-docker-dockerhub.yml b/.github/workflows/deploy-docker-dockerhub.yml
--- a/.github/workflows/deploy-docker-dockerhub.yml
+++ b/.github/workflows/deploy-docker-dockerhub.yml
@@ -1,12 +1,15 @@
 # #
 #   @type               github workflow
-#   @desc               deploys docker container to Dockerhub
 #   @author             Aetherinox
 #   @url                https://github.com/Aetherinox
+#   @usage              deploys docker container to Dockerhub
+#   @secrets            secrets.ADMINSERV_GPG_KEY_ASC                   gpg private key (armored) | BEGIN PGP PRIVATE KEY BLOCK
+#                       secrets.ADMINSERV_GPG_PASSPHRASE                gpg private key passphrase
+#                       secrets.IMAGE_DOCKERHUB_TOKEN                   hub.docker.com access token
 # #
 
-name: "⚙️ Deploy › Dockerhub"
-run-name: "⚙️ Deploy › Dockerhub"
+name: "📦 Deploy › Docker › Dockerhub"
+run-name: "📦 Deploy › Docker › Dockerhub"
 
 # #
 #   Triggers
@@ -46,7 +49,7 @@ on:
             IMAGE_AUTHOR:
                 description:  "🪪 Image Author"
                 required:     true
-                default:      'aetherinox'
+                default:      'antelle'
                 type:         string
 
             # #
@@ -70,7 +73,7 @@ on:
             IMAGE_DOCKERHUB_USERNAME:
                 description:  "🪪 Dockerhub Username"
                 required:     true
-                default:      'aetherinox'
+                default:      'antelle'
                 type:         string
 
             # #
@@ -89,8 +92,8 @@ on:
             #   DISABLE:      release version will be marked as stable / normal release
             # #
 
-            BETA_RELEASE:
-                description:  "🧪 Beta (Pre-release)"
+            DEV_RELEASE:
+                description:  "🧪 Development Release"
                 required:     true
                 default:      false
                 type:         boolean
@@ -109,9 +112,9 @@ on:
 
 env:
     IMAGE_NAME:                 ${{ github.event.inputs.IMAGE_NAME || 'keeweb' }}
-    IMAGE_AUTHOR:               ${{ github.event.inputs.IMAGE_AUTHOR || 'aetherinox' }}
+    IMAGE_AUTHOR:               ${{ github.event.inputs.IMAGE_AUTHOR || 'antelle' }}
     IMAGE_VERSION:              ${{ github.event.inputs.IMAGE_VERSION || '1.19.0' }}
-    IMAGE_DOCKERHUB_USERNAME:   ${{ github.event.inputs.IMAGE_DOCKERHUB_USERNAME || 'aetherinox' }}
+    IMAGE_DOCKERHUB_USERNAME:   ${{ github.event.inputs.IMAGE_DOCKERHUB_USERNAME || 'antelle' }}
     BOT_NAME_1:                 EuropaServ
     BOT_NAME_DEPENDABOT:        dependabot[bot]
     
@@ -158,6 +161,23 @@ jobs:
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
+
+            # #
+            #   Release › Tags › Check Permissions
+            # #
+
+            - name: 'Check Permissions'
+              run: |
+                  find ./ -name 'run' -exec chmod 755 {} \;
+                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
+                  if [ -n "${WRONG_PERM}" ]; then
+                      for i in ${WRONG_PERM}; do
+                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
+                      done
+                      exit 1
+                  else
+                      echo "**** Executable permissions are OK ****"
+                  fi
 
             # #
             #   Release › Tags › Create Tag
@@ -211,6 +231,23 @@ jobs:
                   fetch-depth: 0
 
             # #
+            #   Release › Dockerhub › Check Permissions
+            # #
+
+            - name: 'Check Permissions'
+              run: |
+                  find ./ -name 'run' -exec chmod 755 {} \;
+                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
+                  if [ -n "${WRONG_PERM}" ]; then
+                      for i in ${WRONG_PERM}; do
+                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
+                      done
+                      exit 1
+                  else
+                      echo "**** Executable permissions are OK ****"
+                  fi
+
+            # #
             #   Release › Dockerhub › QEMU › Arm64
             # #
 
@@ -256,10 +293,10 @@ jobs:
                       type=raw,value=latest,enable=false
 
                       #  dispatch       add x1.x.x-arm64
-                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.BETA_RELEASE == false }},priority=300,prefix=,suffix=-arm64,value=${{ env.IMAGE_VERSION }}
+                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == false }},priority=300,prefix=,suffix=-arm64,value=${{ env.IMAGE_VERSION }}
 
                       #  dispatch       add arm64-development
-                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.BETA_RELEASE == true }},priority=300,prefix=,suffix=-development,value=arm64
+                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == true }},priority=300,prefix=,suffix=-development,value=arm64
 
                       #  tag            add tag-arm64
                       type=ref,enable=${{ github.event_name == 'pull_request' || github.event_name == 'push' }},priority=600,prefix=,suffix=-arm64,event=tag
@@ -334,6 +371,23 @@ jobs:
                   fetch-depth: 0
 
             # #
+            #   Release › Dockerhub › Check Permissions
+            # #
+
+            - name: 'Check Permissions'
+              run: |
+                  find ./ -name 'run' -exec chmod 755 {} \;
+                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
+                  if [ -n "${WRONG_PERM}" ]; then
+                      for i in ${WRONG_PERM}; do
+                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
+                      done
+                      exit 1
+                  else
+                      echo "**** Executable permissions are OK ****"
+                  fi
+
+            # #
             #   Release › Dockerhub › QEMU › Amd64
             # #
 
@@ -375,21 +429,21 @@ jobs:
                       ${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
                   tags: |
                       #  latest yes
-                      type=raw,value=latest,enable=${{ !inputs.BETA_RELEASE }}
+                      type=raw,value=latest,enable=${{ !inputs.DEV_RELEASE }}
 
                       #  dispatch       add x1.x.x-amd64
-                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.BETA_RELEASE == false }},priority=300,prefix=,suffix=-amd64,value=${{ env.IMAGE_VERSION }}
+                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == false }},priority=300,prefix=,suffix=-amd64,value=${{ env.IMAGE_VERSION }}
 
                       #  dispatch       add amd64-development
-                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.BETA_RELEASE == true }},priority=300,prefix=,suffix=-development,value=amd64
+                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == true }},priority=300,prefix=,suffix=-development,value=amd64
 
                       #  tag            add tag-arm64
                       type=ref,enable=${{ github.event_name == 'pull_request' || github.event_name == 'push'}},priority=600,prefix=,suffix=-amd64,event=tag
 
                       #  add development tag
-                      type=raw,enable=${{ inputs.BETA_RELEASE }},priority=400,prefix=,suffix=,value=development
+                      type=raw,enable=${{ inputs.DEV_RELEASE }},priority=400,prefix=,suffix=,value=development
                   flavor: |
-                      latest=${{ !inputs.BETA_RELEASE }}
+                      latest=${{ !inputs.DEV_RELEASE }}
 
             # #
             #   Release › Dockerhub › Debug › Amd64
