update

diff --git a/.github/workflows/deploy-docker-github.yml b/.github/workflows/deploy-docker-github.yml
--- a/.github/workflows/deploy-docker-github.yml
+++ b/.github/workflows/deploy-docker-github.yml
@@ -168,6 +168,7 @@ jobs:
 
             - name: 'Check Permissions'
               run: |
+                  find ./ -name 'run' -exec chmod 755 {} \;
                   WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                   if [ -n "${WRONG_PERM}" ]; then
                       for i in ${WRONG_PERM}; do
@@ -228,6 +229,23 @@ jobs:
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
+
+            # #
+            #   Release › Github › Check Permissions
+            # #
+
+            - name: 'Check Permissions'
+              run: |
+                  find ./ -name 'run' -exec chmod 755 {} \;
+                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
+                  if [ -n "${WRONG_PERM}" ]; then
+                      for i in ${WRONG_PERM}; do
+                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
+                      done
+                      exit 1
+                  else
+                      echo "**** Executable permissions are OK ****"
+                  fi
 
             # #
             #   Release › Github › QEMU › Arm64
@@ -348,6 +366,23 @@ jobs:
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
+
+            # #
+            #   Release › Github › Check Permissions
+            # #
+
+            - name: 'Check Permissions'
+              run: |
+                  find ./ -name 'run' -exec chmod 755 {} \;
+                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
+                  if [ -n "${WRONG_PERM}" ]; then
+                      for i in ${WRONG_PERM}; do
+                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
+                      done
+                      exit 1
+                  else
+                      echo "**** Executable permissions are OK ****"
+                  fi
 
             # #
             #   Release › Github › QEMU › Amd64
